### PR TITLE
Update semantic highlighting code in line with the update IDE protocol

### PR DESCRIPTION
**Pull request by ohad**
Adds minor protocol version support

See idris2 [PR#2171](https://github.com/idris-lang/Idris2/pull/2171)'s new spec for [`Bounds`](https://github.com/idris-lang/Idris2/blob/dd8914f627604461632bb530cb734014a47f505f/src/Libraries/Text/Bounded.idr#L9-L16)

~~(wait until we merge #2171 before merging.)~~

### CODE REVIEW

**Comment by jfdm** [comment]
@Ohad Thanks for these updates. They are very much appreciated. Looking at the error, it *is* something I have seen before, and my fix was to drop the older versions of Emacs tested...I am, however, concerned about dropping more versions.  In the past there was a soft rule that we tested against the earliest known Emacs released in Debian Stable/Ubuntu LTS. I have seen this issue discussed [elsewhere](https://github.com/Silex/docker-emacs/issues/56) which may require us to look at how we setup the emacs for testing.

**Comment by jfdm** [comment]
@ohad I have had a look at the issue with emacs, batching, and CIs in the mentioned issue. I think the issue is that, in Emacs, we need to call initialise before we refresh the package contents. I have drafted #548 which might help your issue. If not we can investigate further.

**Comment by jfdm** [comment]
So far so good... the Idris2 tests have completed on time, just waiting for Idris1 one's to complete. Hopefully, this will work. Once the tests have passed we can merge.

**Comment by jfdm** [comment]
Well that was a simple fix. Apologies that this too *soo* long to address, for something so simple.

I have merge this. 

Thanks, as always, for the contributions.

**Comment by ohad** [comment]
Thanks! Don't worry about it, I don't think it was blocking anyone (since they could have used the PR in the meanwhile).

Thanks for the fix!!

**Comment by gallais** [comment]
Ah nice. I was getting really puzzling CI errors on the idris(2)-mode merges so hopefully
that may fix that too.

**Pull request merged**
