### PR TITLE
Add idris2 tests merge

### PR DESCRIPTION
**Pull request by ywata**
Merged latest master as requested by #534. 
- Add make test3 in idris2.yml
- Comment out failed test idris-test2-proof-search
- Emacs version for test updated. 
  - Drop  24.5, update 26.1 -> 26.3, and 27.2 added

### CODE REVIEW

**Comment by jfdm** [comment]
This looks great. A few minor things:

+ [ ] Can we remove the IBC files from the PR please. They are a build artefact from Idris1, better yet would be to add a local `.gitignore` to `test-data` or extend the root `.gitignore`.
+ [ ] Add yourself to the `CONTRIBUTORS` file.

Thanks, your contribution is much much appreciated!

**Comment by jfdm** [comment]
Right, so we do not have a contributors file! I will sort that last request out.

**Comment by ywata** [comment]
Sorry, I did not notice .ibc files. I'll work on it after my work finishes.

**Comment by jfdm** [comment]
Actually, I can do that locally.

Thanks for the PRs they are most welcome.

**Comment by jfdm** [comment]
All done! Thanks for the contributions.

**Pull request merged**
