### PR TITLE
fix byte compilation warnings

### PR DESCRIPTION
**Pull request by jeffersoncarpenter**
This fixes "Warning: `:ok' called as a function" and similar warnings on emacs 24.5.1.

I am not familiar with some elisp features, and am not certain why requiring the cl package fixes the warnings alleging that various keyword symbols, and `t`, are called as functions.  So there could easily a different change that would be better, like a modification to the `idris-rex` function, or somehow getting `inferior-idris.el` to run its `eval-when-compile` statements when it is required by a file getting compiled.

### CODE REVIEW

**Comment by abailly** [comment]
It seems this does not compile on emacs 25, the CI is deceptive. I will push a new PR fixing the CI.

**Comment by jsoo1** [comment]
Looks like the issue was travis configuration. Should this still be merged @abailly ? Sorry this has taken so long.

**Comment by abailly** [comment]
Let's merge I think

**Comment by jsoo1** [comment]
Sounds good.

**Pull request merged**
