### PR TITLE
Use Cask for managing dependencies

### PR DESCRIPTION
**Pull request by marsam**
See: [Why Cask?](https://cask.readthedocs.org/en/latest/guide/introduction.html#introduction-why-cask)

### CODE REVIEW

**Comment by david-christiansen** [comment]
Despite its dismissive tone towards people who are not using it, I'm not very convinced by the Why Cask page. As far as I can see, Cask has three audiences:

1. People wanting to have a bootstrapping `init.el` that ensures its dependencies are present

2. Package developers who want to install dependencies before working on a package

3. People who, for some reason, can't use `package.el`, perhaps due to being stuck on an old Emacs.

For audience 1, there are many solutions, such as @jwiegley's excellent `use-package`, that don't require running an external Python script. For audience 2, Emacs supports `package-install-file` and `package-install-from-buffer` that will also download and install dependencies. Audience 3 used to be all Emacs users, but these days it's a minority, and `idris-mode` doesn't work on old Emacsen anyway.

At the same time, using Cask, we now need to list our dependencies twice: once in the package metadata, and once in the Cask file, and using Cask to run the tests doesn't seem any less verbose than the Makefile, but it introduces another dependency. 

Is there some benefit to Cask for new Emacsen that I'm missing?

**Comment by jwiegley** [comment]
Not to mention that the Travis build process would now download arbitrary code from the Internet and execute it.

**Comment by marsam** [comment]
Hi:
>  For audience 2, Emacs supports package-install-file and package-install-from-buffer that will also download and install dependencies

As a package developer, I mostly prefer to use cask to check a package in isolation, it creates an package.el archive in a .cask directory in which installs the dependencies, and this differs from the archive stored in my ~/.emacs.d/; common uses cases could be: I don't want to install a dependecy globally or when a dependency is installed globally but not declared in the metadata.

Also doesn't polute the Makefile with package.el configuration.

> At the same time, using Cask, we now need to list our dependencies twice: once in the package metadata, and once in the Cask file, and using Cask to run the tests doesn't seem any less verbose than the Makefile, but it introduces another dependency. 

I used it incorrectly. I've updated it for cask read the dependencies from the metadata.

**Comment by abailly** [comment]
Seems like there is no consensus about this so closing it ATM

**Pull request closed without merging**
