### PR TITLE
Use cl-lib macros instead of the cl ones

### PR DESCRIPTION
**Pull request by marsam**

### CODE REVIEW

**Comment by david-christiansen** [comment]
Thanks for this!

Last time I replaced `lexical-let` with Emacs's own now-lexical `let`, I got strange errors at runtime that I haven't had the chance to debug yet, which I attributed to `lexical-let` using some kind of hack behind the scenes that `idris-mode` was relying on. Have you used `idris-mode` for any amount of time with these changes? I'm knee-deep in dissertation-writing, so I can't test them myself for a little while.

**Comment by marsam** [comment]
I haven't found problems so far, but I think this can wait until you have time to check it.

**Comment by david-christiansen** [comment]
All right, next time I'm writing big piles of Idris instead  of piles of LaTeX, I'll take this for a spin and see if things work right. It'd also be nice to replace all the custom pattern matching macros with pcase eventually, but that's a bit of a long-term project for me right now!

**Comment by abailly** [comment]
I have played with this PR for some time and all seems fine on Emacs 25.2. I suggest we merge this.

**Pull request merged**
