### PR TITLE
Don't run evil keybindings initialization by default

### PR DESCRIPTION
**Pull request by BartAdv**
Like we discussed last time.

### CODE REVIEW

**Comment by Melvar** [comment]
Would you perhaps please add appropriate bindings to the configuration that comes with spacemacs if you know what that should look like?

**Comment by BartAdv** [comment]
I plan to do that next. However, I'm a bit slow due to lack of time:)

**Comment by Melvar** [comment]
Thank you anyway. If it gets done at all it’ll help.

**Comment by BartAdv** [comment]
https://github.com/syl20bnr/spacemacs/pull/1664

**Comment by BartAdv** [comment]
Oh, I've messed up something, the build is failing

**Pull request closed without merging**
