### PR TITLE
Remove references to idris-event-buffer-name when idris-log-events is nil

### PR DESCRIPTION
**Pull request by jsoo1**
I think this was introduced in #445

### CODE REVIEW

**Comment by david-christiansen** [comment]
I just restarted the errored Travis build. Looks like it should go through.

Thanks for sending these in! My life is bonkers, but I'm happy with this assuming it works. Do you want a commit bit so that I'm not blocking? We usually want at least one other person reading each PR before merging, but if nobody else is doing it then we need to get it bootstrapped back up again :)

**Comment by jsoo1** [comment]
I don't take the commit bit lightly and I'm certainly a hobbyist. I would like to take it. What are the downsides for the project?

**Comment by david-christiansen** [comment]
Hobbyist is what we all are on this project! I'll add you. The only potential downside is the risk of you doing something terrible to it, which seems like a small risk :-)

**Comment by david-christiansen** [comment]
Invite sent.

**Comment by jsoo1** [comment]
Thanks!

**Pull request merged**
