### PR TITLE
Use the same buffer information throughout file load.

### LINKED ISSUE #423: loading file with holes causes error
Reproduce step:
1. create a new file
2. write the following
   
   ``` idris
    test : String
    test = ?hole
   ```
3. run `idris-load-file`

Debugger info:

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   file-name-directory(nil)
>   idris-filename-to-load()
>   idris-update-loaded-region(nil)
>   #[257 "\302 \210\303 \210p\304   \235\203\305 \210\306\307!\210\310!\207" [idris-currently-loaded-buffer idris-warnings-printing idris-make-clean idris-update-options-cache warnings-tree idris-list-compiler-notes run-hooks idris-load-file-success-hook idris-update-loaded-region] 3 "\n\n(fn RESULT)"](nil)
>   #[257 "\300:\203/@A\301=\204!\202_\211:\203'\211@A\211\204\211\302:\203@\262\211:\203\211@A:\203
> @A:\203@A\303=\203 \211:\203  \211@A\211\204:\203@A:\203@A\304=\203\211:\203\211@A\211:\203\211@A\211\204\377:\203\377@A:\203\375@A\305=\203\373\211:\203\373\211@A\211:\203\371\211@A\211\204\367\204\367:\203\367@A\211\204\365\306!\306\307 !\230\203\363\310p   &\210\266\266\266\266\266\266\266\266\266\266\266\266\266\266A\262\202&\302\266\202\262\202\"!\266\202\202_!\266\202\2022\211!\207" [#[257 "\302 \210\303 \210p\304  \235\203\305 \210\306\307!\210\310!\207" [idris-currently-loaded-buffer idris-warnings-printing idris-make-clean idris-update-options-cache warnings-tree idris-list-compiler-notes run-hooks idris-load-file-success-hook idris-update-loaded-region] 3 "\n\n(fn RESULT)"] :highlight-source nil :filename :start :end file-name-nondirectory buffer-file-name idris-highlight-input-region] 48 "\n\n(fn RESULT)"](nil)
>   #[1028 "\211\211@A\300\301\"\2035\211\211G\302U\203\211@\202 \303\304\305GD\"J\2050Jq\210J!\266\202\202\204\300\306\"\203\200\211\211\203J\211A\262\242\202Q\303\304\305GD\"\211A\262\242\203f\303\304\305\307G\D\"\210    J\203wJq\210    J!\210\310\311\"\266\203\202\204\312\313\"\207" [eql :ok 1 signal wrong-number-of-arguments nil :error 2 message "Evaluation returned an error: %s." error "ELISP destructure-case failed: %S"] 15 "\n\n(fn G69925 G69926 G69927 G69921)"](--failure-cont-- --buffer-- --cont-- %28:ok nil%29)
>   apply(#[1028 "\211\211@A\300\301\"\2035\211\211G\302U\203\211@\202 \303\304\305GD\"J\2050Jq\210J!\266\202\202\204\300\306\"\203\200\211\211\203J\211A\262\242\202Q\303\304\305GD\"\211A\262\242\203f\303\304\305\307G\D\"\210  J\203wJq\210    J!\210\310\311\"\266\203\202\204\312\313\"\207" [eql :ok 1 signal wrong-number-of-arguments nil :error 2 message "Evaluation returned an error: %s." error "ELISP destructure-case failed: %S"] 15 "\n\n(fn G69925 G69926 G69927 G69921)"] --failure-cont-- --buffer-- --cont-- (:ok nil))
>   (lambda (&rest --cl-rest--) (apply (quote #[1028 "\211\211@A\300\301\"\2035\211\211G\302U\203\211@\202 \303\304\305GD\"J\2050Jq\210J!\266\202\202\204\300\306\"\203\200\211\211\203J\211A\262\242\202Q\303\304\305GD\"\211A\262\242\203f\303\304\305\307G\D\"\210  J\203wJq\210    J!\210\310\311\"\266\203\202\204\312\313\"\207" [eql :ok 1 signal wrong-number-of-arguments nil :error 2 message "Evaluation returned an error: %s." error "ELISP destructure-case failed: %S"] 15 "\n\n(fn G69925 G69926 G69927 G69921)"]) (quote --failure-cont--) (quote --buffer--) (quote --cont--) --cl-rest--))((:ok nil))
>   idris-dispatch-event((:return (:ok nil) 42) #<process Idris IDE support>)
>   idris-connection-available-input(#<process Idris IDE support>)
>   idris-output-filter(#<process Idris IDE support> "00001a(:set-prompt \"*hello\" 42)\n000016(:return (:ok ()) 42)\n")

### PR DESCRIPTION
**Pull request by jsoo1**
Fixes a race condition when using popwin. When file is done loading (current-buffer) will be nil.

A fresher version of https://github.com/idris-hackers/idris-mode/pull/483

Closes #423

### CODE REVIEW

**Comment by jsoo1** [comment]
Should I be using something else? (#158)

**Comment by jfdm** [comment]
Sorry about the delay in someone checking your PR. Although I am an emacs user I do not know too much about the internals. 

If you are able to recheck that yoru PR works then let me know and I will merge.

**Comment by keram** [comment]
Hello @jsoo1 
if you get chance would you be able test if the issue you experienced is still present in the "main" branch.
There is slight chance it may be fixed and if not I would be inclined to close this PR in favour of fresh fix.

**Comment by jsoo1** [comment]
I'm more prone to closing. It's been long enough and enough changes have happened I don't think it applies any longer.  Thank flyby for keeping it open for so long!

**Pull request closed without merging**
